services:
  - type: web
    name: swiftmail-pusher
    env: node
    plan: free
    rootDir: render-pusher
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUSH_SECRET
        value: sw_push_78x2y9z_secure_v1
      - key: NODE_VERSION
        value: 18.0.0
